server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /admin/ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
        try_files $uri $uri/ /admin/index.html;
    }

    location /portal {
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
        try_files $uri $uri/ /admin/index.html;
    }
}
